### ISSUE TITLE
Follow Feature

### ISSUE THREAD

**Issue by Elizura** [Merwan-J/AskAnything#8]
Allow users to follow other users or specific questions categories to receive updates and have an entire section dedicated to display questions only from users/categories they follow.

**Comment by Elizura** [comment]
In addition of followers, do I need to add following, just to know which users a person is following?

**Comment by Merwan-J** [comment]
Yes That should also be implemented

**Comment by Merwan-J** [comment]
> In addition of followers, do I need to add following, just to know which users a person is following?

Yes following should also be implemented
